site_name: wrappers
site_url: https://supabase.github.io/wrappers
site_description: A PostgreSQL extension for connecting to external data sources

repo_name: supabase/wrappers
repo_url: https://github.com/supabase/wrappers

nav:
    - Welcome: 'index.md'
    - Installation: 'installation.md'
    - Wrappers:
      - Airtable: 'airtable.md'
      - BigQuery: 'bigquery.md'
      - ClickHouse: 'clickhouse.md'
      - Firebase: 'firebase.md'
      - Logflare: 'logflare.md'
      - S3: 's3.md'
      - Stripe: 'stripe.md'
    - Contributing: 'contributing.md'

theme:
    name: 'material'
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/wrappers
    features:
      - navigation.expand  
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
